# MongoDB collection name constants

USERS = "users"
RESUMES = "resumes"
SKILLS = "skills"
JOB_ROLES = "job_roles"
JOB_DESCRIPTIONS = "job_descriptions"
JD_VERIFICATIONS = "jd_verifications"
ROLE_REQUIREMENTS = "role_requirements"
QUESTIONS = "questions"
TOPICS = "topics"
TOPIC_QUESTIONS = "topic_questions"
SESSIONS = "sessions"
ANSWERS = "answers"
RESULTS = "results"
